# Default Cranked Config, last edited in version 0.0.1
MySQL:
  Enable: false
  Host: 127.0.0.1
  Port: 3306
  Database: minecraft
  Username: user
  Password: pass
Settings:
  Global:
    Time:
      PreGame: 10
      Game: 300
      Waiting Status Update: 60
    Playing:
      Max Players: 20
    Speed:
      Bonus Well Waiting: 0.6
      Bonus Per Kill: 0.075
    Score:
      Per Kill: 10
    Points:
      Max Points: 30
    Misc:
      Can Drop Items: false
      Can Loose Food: false
    Auto Start:
      Required Players: 4
    Equipment:
      Helmet: '298'
      Chest: '299'
      Legs: '300'
      Feet: '301'
      Items:
        - 272-34@100
        - '261'
        - 262,64
    ScoreBoard:
      Waiting:
        - " "
        - " Waiting For"
        - " More Players"
        - " "
        - "&a&lPlayers In:"
        - "&f<players>"
        - " "
        - "&lPlayers Needed:"
        - "&f<neededplayers>"
        - " "
      Started:
        - " "
        - "&9&lPoints:"
        - "&9&l<points>"
        - " "
        - "&a&lKills:"
        - "&a&o<kills>"
        - " "
        - "&c&lDeaths:"
        - "&c&o<deaths>"
        - " "
        - "&6&lKill Streak:"
        - "&6&o<killstreak>"
        - " "
Blocks to use for join GUI:
- STONE
- GRASS
- DIRT
- COBBLESTONE
- WOOD
- BEDROCK
- SAND
- GRAVEL
- GOLD_ORE
- IRON_ORE
- COAL_ORE
- LOG
- SPONGE
- LAPIS_ORE
- LAPIS_BLOCK
- DISPENSER
- SANDSTONE
- NOTE_BLOCK
- WOOL
- GOLD_BLOCK
- IRON_BLOCK
- DOUBLE_STEP
- BRICK
- BOOKSHELF
- MOSSY_COBBLESTONE
- OBSIDIAN
- MOB_SPAWNER
- DIAMOND_ORE
- DIAMOND_BLOCK
- WORKBENCH
- FURNACE
- BURNING_FURNACE
- REDSTONE_ORE
- GLOWING_REDSTONE_ORE
- SNOW_BLOCK
- CLAY
- JUKEBOX
- PUMPKIN
- NETHERRACK
- SOUL_SAND
- JACK_O_LANTERN
- LOCKED_CHEST
- MONSTER_EGGS
- SMOOTH_BRICK
- HUGE_MUSHROOM_1
- HUGE_MUSHROOM_2
- MELON_BLOCK
- MYCEL
- NETHER_BRICK
- ENDER_PORTAL_FRAME
- ENDER_STONE
- REDSTONE_LAMP_OFF
- REDSTONE_LAMP_ON
- WOOD_DOUBLE_STEP
- EMERALD_ORE
- EMERALD_BLOCK
- COMMAND
- QUARTZ_ORE
- QUARTZ_BLOCK
- DROPPER
- STAINED_CLAY
- HAY_BLOCK
- HARD_CLAY