# Default Cranked Config, last edited in version 0.0.3
MySQL:
  Enable: false
  Host: 127.0.0.1
  Port: 3306
  Database: minecraft
  Username: user
  Password: pass
Check For Updates:
  Enabled: true
Settings:
  Global:
    Time:
      PreGame: 10
      Game: 300
      Waiting Status Update: 60
    Score:
      Per Kill: 10
    Points:
      Max Points: 30
    Misc:
      Can Drop Items: false
      Can Loose Food: false
    Game:
      Max Players: 20
    Auto Start:
      Required Players: 4
    Default Kit: Guard
    ScoreBoard:
      Waiting:
        - " "
        - " Waiting For"
        - " More Players"
        - " "
        - "&a&lPlayers In:"
        - "&f<players>"
        - " "
        - "&lPlayers Needed:"
        - "&f<neededplayers>"
        - " "
      Started:
        - " "
        - "&9&lPoints:"
        - "&9&l<points>"
        - " "
        - "&a&lKills:"
        - "&a&o<kills>"
        - " "
        - "&c&lDeaths:"
        - "&c&o<deaths>"
        - " "
        - "&6&lKill Streak:"
        - "&6&o<killstreak>"
        - " "