name: Cranked
description: COD Ghosts Cranked for MC
main: me.sniperzciinema.cranked.Main
version: 0.0.2
author: xXSniperzzXx_SD
commands:
  Cranked:
    description: The basic command for Cranked 
    aliases: [crank, cr]
permissions:

  Cranked.Join:
    default: true
    children:
      Cranked.Leave: true
      Cranked.Arenas: true
      Cranked.List: true
      
  Cranked.Admin:
    default: op
    children:
      Cranked.SetUp: true
      
  Cranked.SetUp:
    children:
      Cranked.Spawns: true
      Cranked.SetSpawn: true
      Cranked.TpSpawn: true
      Cranked.DelSpawn: true
      Cranked.Create: true
      Cranked.Remove: true