name: Cranked
description: COD Ghosts Cranked for MC
main: me.sniperzciinema.cranked.Cranked
version: 1.0.1
author: SniperzCiinema
commands:
  Cranked:
    description: The basic command for Cranked 
    aliases: [crank, cr]
permissions:

  Cranked.Join:
    default: true
    children:
      Cranked.Leave: true
      Cranked.Arenas: true
      Cranked.List: true
      Cranked.Help: true
      Cranked.Info: true
      Cranked.Kits: true
      Cranked.Top: true
      Cranked.Suicide: true
      
  Cranked.Admin:
    default: op
    children:
      Cranked.SetUp: true